name: laugh1
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  google_sign_in: ^5.4.2
  dio: ^4.0.6
  image_picker: ^0.8.6
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  sizer: ^2.0.15
  lottie: ^2.0.0
  shimmer: ^2.0.0
  readmore: ^2.2.0
  google_fonts: ^3.0.1
  flutter_typeahead: ^4.1.1
  connectivity_plus: ^2.3.4
  shared_preferences: ^2.0.15
  mocktail: ^0.3.0
  flutter_native_splash: ^2.2.15
  flutter_svg: ^1.1.6
  introduction_screen: ^3.0.2
  get_storage: ^2.0.3
  pull_to_refresh: ^2.0.0
  font_awesome_flutter: ^10.2.1
  cached_network_image: ^3.2.3
  persistent_bottom_nav_bar: ^5.0.2
  step_progress_indicator: 1.0.2
  smooth_page_indicator: ^1.0.0+2
  loading_animation_widget: ^1.2.0+3
  flutter_gifimage: ^1.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter_native_splash: 
  image: assets/image/light_mode.png
  color: '#ffffff'
  image_dark: assets/image/dark_mode.png
  color_dark: '#212121'
  android_12: 
    image: assets/image/light_mode.png
    image_dark: assets/image/dark_mode.png


flutter: 
  assets: 
    - assets/image/
    - assets/icons/
    - assets/lottie/
  uses-material-design: true

